# App_utn


Esto es lo que estaba en el archivo que te daba error --------------------------------------------------------------

--Conda Info

active environment : entornoVirtual
    active env location : C:\Users\54116\anaconda3\envs\entornoVirtual
            shell level : 2
       user config file : C:\Users\54116\.condarc
 populated config files : C:\Users\54116\.condarc
          conda version : 4.9.2
    conda-build version : 3.18.11
         python version : 3.8.3.final.0


-- Version python entorno virtual

(entornoVirtual) C:\Users\54116\Downloads\AplicacionCRUD_utn\Aplicacion\appcrud>python --version
Python 3.8.5


-- Version de Django

(entornoVirtual) C:\Users\54116\Downloads\AplicacionCRUD_utn\Aplicacion\appcrud>python -m django --version
3.0.8

-----------------------------------------------------------------------------------------------------------------------

## DOWNGRADE ##

(entornoVirtual) C:\Users\54116\Desktop\curso utn\AplicacionCRUD\Aplicacion\appcrud>python --version
Python 3.8.5

(entornoVirtual) C:\Users\54116\Desktop\curso utn\AplicacionCRUD\Aplicacion\appcrud>python -m django --version
2.2.17

(entornoVirtual) C:\Users\54116\Desktop\curso utn\AplicacionCRUD\Aplicacion\appcrud>conda info

     active environment : entornoVirtual
    active env location : C:\Users\54116\anaconda3\envs\entornoVirtual
            shell level : 2
       user config file : C:\Users\54116\.condarc
 populated config files : C:\Users\54116\.condarc
          conda version : 4.9.2
    conda-build version : 3.18.11
         python version : 3.8.3.final.0
